### ISSUE TITLE
안녕하세요. 연락 드릴 방법이 없어 이슈 남깁니다.

### ISSUE THREAD

**Issue by abwarten** [Capstone-Noodles/Noodles-Server#55]
최근 팔로우 주셔서 잘 보고 있습니다
다름이 아니라 DB 키 값이 보여서 추후 문제가 될 수도 있을 것 같아서 이슈 남기게 되었습니다

.gitignore에 추가 하시고, 팀원 분들께 파일로 공유 드리는 것을 추천 드립니다

쓰고 보니 괜히 오지랖 부리는 것 같네요... ㅎㅎ;
항상 건강하시고, 하시는 일 잘 되시길 기원합니다 :)

확인 하시면 이슈는 지워주세요
감사합니다 :)

**Comment by wormjoo** [comment]
확인하고 .gitignore에 추가했습니다~
감사합니다 :)
